package timesignal

import "math"

// Tone design
//
// The pure 880 Hz beep mode ("time_signal", generated by FFmpeg's sine source)
// was judged the most pleasant, so the spoken 117 mode reuses the same pitch:
//
//	:07 :08 :09  short 880 Hz preview pips (100 ms)
//	:00          880 Hz mark tone (800 ms) with a bell-like decay
//
// Every edge uses a raised-cosine ramp so there are no clicks, and the peak
// levels are kept moderate so that the mixed voice + tone never clips.
const (
	ToneFrequencyHz = 880.0

	pipDurationMs   = 100
	pipRampMs       = 15
	pipAmplitude    = 0.28
	markDurationMs  = 800
	markAttackMs    = 15
	markSustainMs   = 250
	markDecayTauMs  = 200.0
	markAmplitude   = 0.32
	previewFirstSec = 7 // pips play at :07, :08, :09 of each 10-second block
)

// raisedCosineRamp returns a smooth 0→1 envelope value for x in [0,1].
func raisedCosineRamp(x float64) float64 {
	if x <= 0 {
		return 0
	}
	if x >= 1 {
		return 1
	}
	return 0.5 - 0.5*math.Cos(math.Pi*x)
}

// pipEnvelope is the amplitude envelope of a preview pip at tMs milliseconds.
func pipEnvelope(tMs float64) float64 {
	if tMs < 0 || tMs >= pipDurationMs {
		return 0
	}
	if tMs < pipRampMs {
		return raisedCosineRamp(tMs / pipRampMs)
	}
	if tMs > pipDurationMs-pipRampMs {
		return raisedCosineRamp((pipDurationMs - tMs) / pipRampMs)
	}
	return 1
}

// markEnvelope is the amplitude envelope of the mark tone at tMs milliseconds.
func markEnvelope(tMs float64) float64 {
	if tMs < 0 || tMs >= markDurationMs {
		return 0
	}
	if tMs < markAttackMs {
		return raisedCosineRamp(tMs / markAttackMs)
	}
	if tMs < markSustainMs {
		return 1
	}
	// Exponential decay, then a short raised-cosine tail so the tone ends at zero.
	env := math.Exp(-(tMs - markSustainMs) / markDecayTauMs)
	tailMs := float64(markDurationMs) - tMs
	if tailMs < pipRampMs {
		env *= raisedCosineRamp(tailMs / pipRampMs)
	}
	return env
}

// ToneSample returns the tone value in [-1,1] for the given position within a
// minute: secOfMinute in [0,59] and sampleInSec in [0,sampleRate).
func ToneSample(secOfMinute, sampleInSec, sampleRate int) float64 {
	tMs := float64(sampleInSec) * 1000.0 / float64(sampleRate)
	phase := 2.0 * math.Pi * ToneFrequencyHz * float64(sampleInSec) / float64(sampleRate)

	pos := secOfMinute % AnnouncePeriodSec
	switch {
	case pos == 0:
		return math.Sin(phase) * markEnvelope(tMs) * markAmplitude
	case pos >= previewFirstSec:
		return math.Sin(phase) * pipEnvelope(tMs) * pipAmplitude
	default:
		return 0
	}
}

// RenderTones mixes the time-signal tones into dst. firstSampleInMinute is
// the index (in samples, at sampleRate) of dst[0] measured from the start of
// the current minute, so that a chunk crossing a second boundary is handled.
func RenderTones(dst []int16, firstSampleInMinute, sampleRate int) {
	samplesPerMinute := sampleRate * 60
	for i := range dst {
		abs := (firstSampleInMinute + i) % samplesPerMinute
		sec := abs / sampleRate
		v := ToneSample(sec, abs%sampleRate, sampleRate)
		if v != 0 {
			dst[i] = clampSample(float64(dst[i]) + v*32767)
		}
	}
}

func clampSample(v float64) int16 {
	if v > 32767 {
		return 32767
	}
	if v < -32768 {
		return -32768
	}
	return int16(v)
}
